#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
