#!/usr/bin/env bash
# script that configures a server to listen on port 80 of all the active IP

# modify the default server block config to listen on port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
