#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration

i=0
while [ $i -lt 10 ]
do
 if [ $i -eq 4 ]
 then
  echo "bad luck"
 elif [ $i -eq 8 ]
 then
  echo "good luck"
 fi
  echo "Best School"
  (( i++ ))
done
