#!/usr/bin/env bash
# script that configures nginx so that nginx is runing as an nginx user
id -u nginx &>/dev/null || useradd nginx
sed -i 's/user\s*www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/www/html
sudo -u nginx service nginx start
