#!/usr/bin/env bash
# script that configures nginx so that nginx is runing as an nginx user
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/www/html
service nginx restart
